name: RL
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - numpy
  - pytorch==2.5.0
  - torchvision==0.20.0
  - torchaudio==2.5.0
  - pytorch-cuda=12.1
  - tqdm
  - pyyaml
  - pip
  - pip:
      - logging
      - wandb
      - nvitop